# config/meta.yml

meta_product_name: "Storiz"
meta_title: "Storiz | Masterpieces made easy"
meta_description: "Plateforme d'écriture créative collaborative et communautaire"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@storizclub"   # required for Twitter Cards
